apiVersion: apps/v1
kind: Deployment
metadata:
  #Deployment name 
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: mywebsite
        image: {{.Values.image}}
        ports:
        - containerPort: 80
