apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.Port}}
    targetPort: {{.Values.targetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}
